apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant
        command: []
        ports:
        - containerPort: 8123
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: certificate-volume
          mountPath: "/certificates"
      volumes:
      - name: config
        hostPath:
          path: {{HOME_ASSISTANT_VOLUME_PATH}}
      - name: certificate-volume
        hostPath:
          path: {{CERTIFICATE_VOLUME_PATH}}
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
  - port: 443
    targetPort: 8123
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: home-assistant-ingress
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 443
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: home-assistant-service
          servicePort: 443