apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant
        command: []
        ports:
        - containerPort: 8123
        volumeMounts:
        - name: config
          mountPath: "/config"
      initContainers:
      - name: wait-for-mqtt
        image: groundnuty/k8s-wait-for:latest
        args: [ 'pod', '-lapp=mqtt' ]
      volumes:
      - name: config
        hostPath:
          path: /var/opt/home-assistant
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
  - port: 80
    targetPort: 8123