apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: letsencrypt
  name: letsencrypt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letsencrypt
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: letsencrypt
    spec:
      containers:
      - image: certbot/certbot:latest
        imagePullPolicy: Always
        name: letsencrypt
        args: [ 'certonly', '-n', '--webroot', '-w', '/var/www/html/', '-d', '{{DOMAIN_NAME}}', '--agree-tos', '--email', '{{DOMAIN_EMAIL}}' ]
        volumeMounts:
        - name: certificates
          mountPath: "/etc/letsencrypt"
        - name: webroot
          mountPath: "/var/www/html"
      volumes:
      - name: certificates
        hostPath:
          path: /var/opt/letsencrypt
      - name: webroot
        hostPath:
          path: /var/www/html