apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
          - name: config
            mountPath: "/etc/nginx/nginx.conf"
      volumes:
      - name: config
        hostPath:
          path: /var/opt/nginx/nginx.conf
          type: File
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: letsencrypt
#   labels:
#     app: letsencrypt
# spec:
#   template:
#     metadata:
#       name: letsencrypt
#       labels:
#         app: letsencrypt
#     spec:
#       containers:
#       - image: sjenning/kube-nginx-letsencrypt:0.8.1-1
#         name: letsencrypt
#         imagePullPolicy: Always
#         ports:
#         - name: letsencrypt
#           containerPort: 80
#         env:
#         - name: DOMAINS
#           value: {{DOMAIN_NAME}}
#         - name: EMAIL
#           value: {{DOMAIN_EMAIL}}
#         - name: SECRET
#           value: nginx-secret
#         - name: DEPLOYMENT
#           value: nginx
#       restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: nginx
# spec:
#   tls:
#   - hosts:
#     - {{DOMAIN_NAME}}
#     secretName: nginx-secret
#   rules:
#   - host: {{DOMAIN_NAME}}
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: home-assistant-service
#           servicePort: 80
#       - path: /.well-known
#         backend:
#           serviceName: letsencrypt-service
#           servicePort: 80