homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.8846
  longitude: 2.2697
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 35
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize:
    sensor.ph_meter:
      icon: mdi:flask-empty-outline

    switch.ph_pump:
      icon: mdi:water-pump

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# References the mqtt-service from mqtt.yml
mqtt:
  broker: mqtt-service

http:
  api_password: password
  ssl_certificate: /certificates/fullchain.pem
  ssl_key: /certificates/privkey.pem
  base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: random
    name: "PH Meter"
    maximum: 14
    unit_of_measurement: PH
  - platform: random
    name: "Thermometer"
    maximum: 40
    unit_of_measurement: °C

switch:
  - platform: command_line
    switches:
      ph_pump:
        command_on: echo "on" > /tmp/ph_pump.log
        command_off: echo "off" > /tmp/ph_pump.log

group:
  default_view:
    view: yes
    entities:
      - group.sensors
      - group.pumps

  sensors:
    name: Sensors
    entities:
      - sensor.ph_meter
      - sensor.thermometer

  pumps:
    name: Pumps
    entities:
      - switch.ph_pump


# Text to speech
tts:
  - platform: google

# Cloud
cloud:

automation:
  - alias: 'Stabilize the PH'
    trigger:
      - platform: numeric_state
        entity_id: sensor.ph_meter
        below: 7
    action:
      - service: switch.turn_on
        entity_id: switch.ph_pump




#script: !include scripts.yaml
