---
- hosts: home-assistant
  become: yes

  tasks:
    - name: Create the configuration directory
      file:
        path: /home/homeassistant/.home-assistant
        owner: homeassistant
        state: directory

    - name: Setup the Home Assistant configuration
      template:
        src: ../config/home-assistant/configuration.yaml.j2
        dest: /home/homeassistant/.home-assistant/configuration.yaml
        owner: homeassistant
        group: homeassistant
        mode: 0644

    - name: Create the virtual environment and setup Home Assistant
      shell: |
        python3 -m venv /home/homeassistant/home-assistant
        cd /home/homeassistant/home-assistant
        . bin/activate
        python3 -m pip install wheel
        python3 -m pip install --upgrade homeassistant

    - name: Set Home Assistant's directory's ownership
      file: 
        path: /home/homeassistant/home-assistant
        state: directory
        owner: homeassistant
        recurse: yes

