---
- hosts: home-assistant
  become: yes
  gather_facts: yes

  tasks:
    - name: Adding Debian FTP PUBKEY
      block:
      - apt_key:
          keyserver: pgpkeys.mit.edu
          id: 8B48AD6246925553
      - apt_key:
          keyserver: pgpkeys.mit.edu
          id: 7638D0442B90D010

    - name: Add Debian Stretch backport
      apt_repository:
        repo: deb http://ftp.debian.org/debian stretch-backports main
        state: present
      when: ansible_distribution_release == 'stretch'
    
    - name: Add Debian Jessie backport
      apt_repository:
        repo: deb http://ftp.debian.org/debian jessie-backports main
        state: present
      when: ansible_distribution_release == 'jessie'

    - name: Upgrade system
      apt: 
        upgrade: dist
        update_cache: yes

    - name: Install Certbot
      apt: 
        name: certbot
        state: latest
        default_release: stretch-backports
      when: ansible_distribution_release == 'stretch'

    - name: Install Certbot
      apt: 
        name: certbot
        state: latest
        default_release: squeeze-backports
      when: ansible_distribution_release == 'jessie'

    - name: Install Python 3 virtual environment
      apt: 
        name: python3-venv
        state: latest

    - name: Install FFMPEG
      apt: 
        name: ffmpeg
        state: latest

    - name: Install PIP
      shell: |
        wget https://bootstrap.pypa.io/get-pip.py
        python3 get-pip.py

    - name: Create certificate
      shell: certbot certonly --standalone --preferred-challenges http -d {{ domain_name }} -m {{ letsencrypt_email }} --agree-tos
      args:
        creates: /etc/letsencrypt/live/{{ domain_name }}

    - name: Setting up certificate rights
      file: 
        path: /etc/letsencrypt/
        state: directory
        recurse: true
        owner: homeassistant
        mode: 0744

    - name: Create renewal cron
      cron:
        name: "Certificate renewal"
        special_time: daily
        job: certbot renew --preferred-challenges http --pre-hook "systemctl stop home-assistant" --post-hook "systemctl start home-assistant"
