apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant
        ports:
        - containerPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
  - port: 80
    targetPort: 8123
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: home-assistant-ingress
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: kubernetes.local
    http:
      paths:
      - path: /
        backend:
          serviceName: home-assistant-service
          servicePort: 80